database:
  mongo:
    uri: ""
    db: "economy"

starting-balance: 100.0

moneynote:
  item:
    material: PAPER
    name: '&a$%amount% Money Note'
    lore:
      - '&fRight click this note'
      - '&fto redeem the money.'
  redeem-message: '&aYou have successfully redeemed a $%amount% Money Note!'

balance-message:
  - '&aWallet Balance: %bal%'
  - '&aBank Balance: %bank_bal%'
insufficient-funds-message: '&cInsufficient funds.'
pay-messages:
  sender: '&aSuccessfully paid %target% $%amount%!'
  target: '&a%sender% paid you $%amount%!'

bank-help-messsage:
  - '&a/bank - View Bank Help Message.'
  - '&a/bank withdraw <amount> - Withdraw Bank Balance to Wallet.'
  - '&a/bank deposit <amount> - Deposit Wallet Balance to Bank.'
bank-deposit-message: '&aSuccessfully deposited $%amount% to Bank.'
bank-withdraw-message: '&aSuccessfully withdrew $%amount% from Bank.'

eco-help-message:
  - '&a/eco - View Economy Admin Help Message.'
  - '&a/eco set <player> <amount> - Set Player Balance.'
  - '&a/eco add <player> <amount> - Add to Player Balance.'
  - '&a/eco remove <player> <amount> - Remove from Player Balance.'

drop-money-on-death: true